title: Rubem Mota
description: Personal Blog
author: Rubem Mota
logo: /static/img/avatar.png
github: https://github.com/rubemlrm
about: Programador / Administrador de Sistemas

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: rubemlrmcom
google_analytics: 'UA-39203492-1'

share:
  twitter_username: rubemlrm
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
