#Jekyll general configs
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/page:num/"
plugins:
  - jekyll-gist
  - jekyll-paginate

# Site Author settings
title: Rubem Mota
email: rubemmota89@gmail.com
tagline: Software Developer
description: Software Developer
author:
  name: Rubem Mota
  url: "rubemlrm.me"

#theme settings
allowsearch: true
sidebar_home_link:  true


disqus:
  shortname: rubemlrmcom
google_analytics: 'UA-39203492-1'

# social settings
github_url: https://github.com/rubemlrm
gitlab_url: https://gitlab.com/u/rubemlrm
linkedin_url: https://www.linkedin.com/in/rubemlrm
twitter_url: https://twitter.com/rubemlrm

enableTags: true
tagarray: []
